repos:
  - repo: https://github.com/ambv/black
    rev: 23.12.0
    hooks:
      - id: black
        language_version: python3.11
        stages: [ commit ]
        args: [ '-v',  '-S', '--line-length', '80' ]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.10.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-angular' ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy-check
        stages: [commit]
        types: [python]
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pycqa/isort
    rev: 5.13.1
    hooks:
      - id: isort
        name: isort (python)
        args: [ '--profile', 'black', '--show-config']
