repos:
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        stages: [ commit ]
        args: [ '-v',  '-S', '--line-length', '80' ]
  - repo: https://github.com/Botpy/pre-commit-pylint
    rev: v0.0.3
    hooks:
      - id: pylint-py3k
      - id: pylint-score-limit
        args:
        - --limit=9.5
        - --rcfile=./.pylintrc
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.5.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        additional_dependencies: [ '@commitlint/config-angular' ]
  - repo: local
    hooks:
      - id: mypy
        name: mypy-check
        stages: [commit]
        types: [python]
        entry: mypy .
        language: system
        pass_filenames: false
        always_run: true
