version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: refuapp
      POSTGRES_USER: refuapp_user
      POSTGRES_PASSWORD: refuapp_password

  refuapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - postgres:docker-mysql
    environment:
      DATABASE_URL: postgresql+psycopg2://refuapp_user:refuapp_password@docker-mysql:5432/refuapp
    depends_on:
      - postgres
    ports:
      - "8000:8000"
