version: '3'
services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  refuapp-backend:
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - postgres:docker-mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: docker-mysql
      JWT_KEY: ${JWT_KEY}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
